https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/appendix-d-pandas.ipynb

In [3]:
import numpy as np
import pandas as pd

In [4]:
# numpy version
np.__version__

'1.19.5'

In [5]:
# pandas version
pd.__version__

'1.3.2'

## READ CAR DATA

In [7]:
df = pd.read_csv('data.csv')

In [10]:
df.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

In [9]:
# Summary analysis
df.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [11]:
# unique values count
df.nunique()

Make                   48
Model                 915
Year                   28
Engine Fuel Type       10
Engine HP             356
Engine Cylinders        9
Transmission Type       5
Driven_Wheels           4
Number of Doors         3
Market Category        71
Vehicle Size            3
Vehicle Style          16
highway MPG            59
city mpg               69
Popularity             48
MSRP                 6049
dtype: int64

In [13]:
# unique value count of Make
df.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

### Average price of BMW

In [15]:
df.groupby('Make').MSRP.mean().round(2)

Make
Acura              34887.59
Alfa Romeo         61600.00
Aston Martin      197910.38
Audi               53452.11
BMW                61546.76
Bentley           247169.32
Bugatti          1757223.67
Buick              28206.61
Cadillac           56231.32
Chevrolet          28350.39
Chrysler           26722.96
Dodge              22390.06
FIAT               22670.24
Ferrari           238218.84
Ford               27399.27
GMC                30493.30
Genesis            46616.67
HUMMER             36464.41
Honda              26674.34
Hyundai            24597.04
Infiniti           42394.21
Kia                25310.17
Lamborghini       331567.31
Land Rover         67823.22
Lexus              47549.07
Lincoln            42839.83
Lotus              69188.28
Maserati          114207.71
Maybach           546221.88
Mazda              20039.38
McLaren           239805.00
Mercedes-Benz      71476.23
Mitsubishi         21240.54
Nissan             28583.43
Oldsmobile         11542.54
Plymouth       

## Missing values

In [16]:
df.isnull()

Make  Model   Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
0      False  False  False             False      False             False   
1      False  False  False             False      False             False   
2      False  False  False             False      False             False   
3      False  False  False             False      False             False   
4      False  False  False             False      False             False   
...      ...    ...    ...               ...        ...               ...   
11909  False  False  False             False      False             False   
11910  False  False  False             False      False             False   
11911  False  False  False             False      False             False   
11912  False  False  False             False      False             False   
11913  False  False  False             False      False             False   

       Transmission Type  Driven_Wheels  Number of Doors  Market Category  \
0                  False          False            False            False   
1                  False          False            False            False   
2                  False          False            False            False   
3                  False          False            False            False   
4                  False          False            False            False   
...                  ...            ...              ...              ...   
11909              False          False            False            False   
11910              False          False            False            False   
11911              False          False            False            False   
11912              False          False            False            False   
11913              False          False            False            False   

       Vehicle Size  Vehicle Style  highway MPG  city mpg  Popularity   MSRP  
0             False          False        False     False       False  False  
1             False          False        False     False       False  False  
2             False          False        False     False       False  False  
3             False          False        False     False       False  False  
4             False          False        False     False       False  False  
...             ...            ...          ...       ...         ...    ...  
11909         False          False        False     False       False  False  
11910         False          False        False     False       False  False  
11911         False          False        False     False       False  False  
11912         False          False        False     False       False  False  
11913         False          False        False     False       False  False  

[11914 rows x 16 columns]

In [17]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

https://www.geeksforgeeks.org/ways-to-filter-pandas-dataframe-by-column-values/

In [18]:
# filter by year >= 2015
filtered_df = df.loc[df['Year'] >= 2015] 

In [19]:
filtered_df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [23]:
mean_hp_before = df['Engine HP'].mean()
print(round(mean_hp_before))

249


In [24]:
# fill null of engine HP with mean
df['Engine HP'].fillna(df['Engine HP'].mean())

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [25]:
mean_hp_after = df['Engine HP'].mean()
print(round(mean_hp_after))

249


In [27]:
sub_df = df.loc[df['Make'] == 'Rolls-Royce'] 

In [31]:
sub_df = sub_df[["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()
sub_df

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

## Numpy https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/appendix-c-numpy.ipynb

In [33]:
sub_df['Engine HP'].values

array([325., 563., 563., 563., 322., 453., 624.])

In [35]:
# get the underlining array
X = sub_df.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [36]:
# transpose X
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [38]:
# multiplication 
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [39]:
# inverse XTX
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [40]:
XTXinv.sum()

0.032212320677486125

## Q7

In [41]:
# create an array y
elements = [1000, 1100, 900, 1200, 1000, 850, 1300]
y = np.array(elements)
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [42]:
# Multiply the inverse of XTX with the transpose of X, 
# and then multiply the result by y. Call the result w.
w = XTXinv.dot(X.T).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])